### ISSUE TITLE
Minimum GPU requirement for a full fine-tuning 

### ISSUE THREAD

**Issue by lkluo** [NicholasCao/ChatBLOOM#1]
Have you tested how many GPU RAM is required for a full fine-tuning? Thanks.

**Comment by NicholasCao** [comment]
When I set batch_size=1, accumulation_steps=8, max_len=512, which requires 28G GPU RAM  in GPU #0

You can adjust these hyperparameters to reduce GPU RAM: batch_size, accumulation_steps, max_len, pretrain (default is 'bigscience/bloom-1b7', you can use 1b1, 560m...)

**Comment by lkluo** [comment]
> When I set batch_size=1, accumulation_steps=8, max_len=512, which requires 28G GPU RAM in GPU #0
> 
> You can adjust these hyperparameters to reduce GPU RAM: batch_size, accumulation_steps, max_len, pretrain (default is 'bigscience/bloom-1b7', you can use 1b1, 560m...)

Thanks for your quick response. My batch_size had set to 1 and a lower max_len, but still running into OOM on my 32G GPU. Two more questions: 1) have you used fp16 during training and 2) have you tested performance between LoRA and fully fine-tuning?

**Comment by NicholasCao** [comment]
The code uses fp16 and fully fine-tuning by default

**Comment by NicholasCao** [comment]
> > When I set batch_size=1, accumulation_steps=8, max_len=512, which requires 28G GPU RAM in GPU #0
> > You can adjust these hyperparameters to reduce GPU RAM: batch_size, accumulation_steps, max_len, pretrain (default is 'bigscience/bloom-1b7', you can use 1b1, 560m...)
> 
> Thanks for your quick response. My batch_size had set to 1 and a lower max_len, but still running into OOM on my 32G GPU. Two more questions: 1) have you used fp16 during training and 2) have you tested performance between LoRA and fully fine-tuning?

I just updated the default trainging policy, you should make sure you are using zero2, see `scripts/train_sft.sh` for more detail.

**Comment by lkluo** [comment]
great, let me try it over. 
btw, have you tested LoRA training? Seemed not working with similar error in https://github.com/hpcaitech/ColossalAI/issues/3419.

**Comment by NicholasCao** [comment]
> great, let me try it over. btw, have you tested LoRA training? Seemed not working with similar error in [hpcaitech/ColossalAI#3419](https://github.com/hpcaitech/ColossalAI/issues/3419).

We do not use LoRA at all 😅
